### ISSUE TITLE
.sql file with new fields are missig in your push

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#10]
I get an error when I try to edit a Empresa because the trivia or not trivia column is missing.
The same happens with mecanica the table is missing.
You forgot to upload the .sql file.

**Comment by ralphdegoma** [comment]
hmm, i think i did attached it to the email i sent with the updates carl?. But yeah i will replace the sql file in the folder so it can pushed also. Thanks.

**Comment by carlos-segovia** [comment]
Solucionado
