### ISSUE TITLE
Backend - footer update

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#100]
Actualizar el footer, cambiar "desarrollos digitales" por "sietepuentes" con un hyperlink a "www.sietepuentes.com".

![image](https://user-images.githubusercontent.com/35821871/38176406-60af5e80-35c4-11e8-9c56-7cbb7a6f1fd1.png)

**Comment by oswaldopr** [comment]
Hecho.

**Comment by carlos-segovia** [comment]
Listo! Esta el link y funciona.
