### ISSUE TITLE
Backend - Menu items

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#101]
Por favor para facilitar la navegación, agregar los mismos menú items del dashboard al menú que está arriba a la derecha, en vez de link1, link2... ponemos empresas, empleados, partidos, etc....

![image](https://user-images.githubusercontent.com/35821871/38176416-afdab0f4-35c4-11e8-9ba2-62f2ff8ee63b.png)

**Comment by oswaldopr** [comment]
Hecho.

**Comment by carlos-segovia** [comment]
Probado. Funciona OK el menú.
