### ISSUE TITLE
Backend - Empresas editar - Validación de imagenes

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#102]
Al querer editar una empresa se siguen validando los tamaños de imágenes, consulto: es mi caché? yo ya borré e hice hard reload, sin embargo sigo teniendo este inconveniente en chrome, en incógnito, en iE...

![image](https://user-images.githubusercontent.com/35821871/38176508-8868fe0c-35c6-11e8-90a8-1403efdb5d19.png)

**Comment by oswaldopr** [comment]
Yo no tuve este inconveniente. Definitivamente es un tema de caché pero que va más allá del navegador mismo. Algunos proxys, si fuera el caso, poseen la misma funcionalidad de los navegadores en cuanto al caché de las páginas con la intención de reducir el tráfico en "su" red. También, considerar revisar la configuración de cualquier otro dispositivo que filtre los paquetes de datos, en este caso entrantes, como _routers_ o _switches_ ya que alguno de ellos pudiera tener habilitada alguna función similar a la comentada en los proxys.

**Comment by carlos-segovia** [comment]
Lo probé y no tuve inconvenientes.

**Comment by debasishpaul2014** [comment]
cant understand what do you mean

**Comment by robertmurer** [comment]
ok
