### ISSUE TITLE
Frontend - Trivias - Prev/Next buttons

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#103]
Let's please change spelling in buttons

<<Prev    should be     <<Anterior

Next>>  should be     Siguiente >>

![image](https://user-images.githubusercontent.com/35821871/38176881-65306590-35cd-11e8-88c6-fce0dcf6f461.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
ok
