### ISSUE TITLE
Frontend - Predictions

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#104]
1) "Pronosticar" button has some fields in the right that shouldn't be there, refer to screenshot
2) Please make "Pronosticar" button always viewable in the bottom, the scroll should only include matches rows, but button always viewable
3) I think scroll bar will be better if we put in left side
4) Replace "Fecha" wording for "Comienza en: "
5) Please add left / right arrows like slider, so user is able to know will be able to do more predictions in other pages, like champion prediction or best player.

![image](https://user-images.githubusercontent.com/35821871/38177013-c5f6d88a-35cf-11e8-9a05-9ca4dbf36282.png)

**Comment by debasishpaul2014** [comment]
try to check it on the phone, I have checked this , but couldn't findout this issue

**Comment by robertmurer** [comment]
I checked in the phone and all issues are there but not 1st and 3rd one.
In addition, in mobile, I am unable to enter number in the fields, please check

Remaining issues
2) Please make "Pronosticar" button always viewable in the bottom, the scroll should only include matches rows, but button always viewable
4) Replace "Fecha" wording for "Comienza en: "
5) Please add left / right arrows like slider, so user is able to know will be able to do more predictions in other pages, like champion prediction or best player.
6) I am unable to enter numbers in the input fields, I enter numbers but field is blank
7) Timer is not working in mobile

![image](https://user-images.githubusercontent.com/35821871/38221647-0c6c425e-36b7-11e8-92cd-e31a443883c4.png)

**Comment by robertmurer** [comment]
Remaining items:
2) Please make "Pronosticar" button always viewable in the bottom, the scroll should only include matches rows, but button always viewable
5) Please add left / right arrows like slider, so user is able to know will be able to do more predictions in other pages, like champion prediction or best player.


To be checked in iphone not working fine:
4) Replace "Fecha" wording for "Comienza en: "
6) I am unable to enter numbers in the input fields, I enter numbers but field is blank
7) Timer is not working in mobile

**Comment by robertmurer** [comment]
Pronosticar button is still not showing in mobile version:

![image](https://user-images.githubusercontent.com/35821871/38446056-701ef554-39cc-11e8-97f3-f5aab98c5fbc.png)

**Comment by robertmurer** [comment]
Debasish updated today, it was not yet possible to be fixed for him due to slider

**Comment by robertmurer** [comment]
As discussed with Debasish
