### ISSUE TITLE
Frontend - Right side predictions page

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#105]
Debasish,
Please check this is how right side will work in every pages. 
Thanks

[Right side bar predictions frontend.pptx](https://github.com/robertmurer/todosalacancha/files/1868541/Right.side.bar.predictions.frontend.pptx)

![image](https://user-images.githubusercontent.com/35821871/38203831-ea03e4c8-3676-11e8-83a1-7db7a32d6b39.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by carlos-segovia** [comment]
I add my prediction in pronosticos and change to ranking and I could not edit my prediction.
I can only edit the prediction in the page where I added it.

**Comment by robertmurer** [comment]
This is not working as expected.  Seems this right side prediction is only being saved in Trivias page. In other pages it is not being saved.

In addition if I Save in Trivias, then refresh screen, it is not showing my last prediction.

Another remaining item is the search by typing in the first dropdown for player....

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
Remaining:
-[ ] Search while typing in first dropdown
-[ ] Log in database for every time user predicts these dropdowns
-[ ] If (sysdate - match_id 1 kickoff) from "partidos" table <= 23:59:59, the right side dropdowns are disabled.

**Comment by robertmurer** [comment]
@debasishpaul2014 this issue is still pending

**Comment by carlos-segovia** [comment]
Deba, in the ranking page when you save your predictions it didn't appear the message: 
![image](https://user-images.githubusercontent.com/34341691/38569320-4e9e9f36-3cc1-11e8-832b-75479e3dbea1.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
closed as there are new issues covering the same
