### ISSUE TITLE
Frontend - Trivias error

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#106]
Logged in as rmurer9/rmurer9
http://todosalacancha.sietepuentes.com/google/trivias 

Got below error after login and click in "Trivias"

![image](https://user-images.githubusercontent.com/35821871/38221445-ee754120-36b5-11e8-8c2c-96c4b4a2d210.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by carlos-segovia** [comment]
¿Cuál fue el último equipo de la Confederación de Oceanía en clasificarse a una Copa Mundial de la FIFA?

A PHP Error was encountered

Severity: Warning

Message: in_array() expects parameter 2 to be array, null given

Filename: index/trivias.php

Line Number: 135

Backtrace:

File: /home/ftp-user/html/todosalacancha/application/views/index/trivias.php
Line: 135
Function: in_array

File: /home/ftp-user/html/todosalacancha/application/controllers/Index.php
Line: 262
Function: view

File: /home/ftp-user/html/todosalacancha/index.php
Line: 317
Function: require_once
> Tahití

A PHP Error was encountered

Severity: Warning

Message: in_array() expects parameter 2 to be array, null given

Filename: index/trivias.php

Line Number: 135

Backtrace:

File: /home/ftp-user/html/todosalacancha/application/views/index/trivias.php
Line: 135
Function: in_array

File: /home/ftp-user/html/todosalacancha/application/controllers/Index.php
Line: 262
Function: view

File: /home/ftp-user/html/todosalacancha/index.php
Line: 317
Function: require_once
> Nueva Zelanda

A PHP Error was encountered

Severity: Warning

Message: in_array() expects parameter 2 to be array, null given

Filename: index/trivias.php

Line Number: 135

Backtrace:

File: /home/ftp-user/html/todosalacancha/application/views/index/trivias.php
Line: 135
Function: in_array

File: /home/ftp-user/html/todosalacancha/application/controllers/Index.php
Line: 262
Function: view

File: /home/ftp-user/html/todosalacancha/index.php
Line: 317
Function: require_once
> Islas Feroe

¿Cuáles equipos han organizado la Copa Mundial de la FIFA en más de una ocasión?

A PHP Error was encountered

Severity: Warning

Message: in_array() expects parameter 2 to be array, null given

Filename: index/trivias.php

Line Number: 135

Backtrace:

File: /home/ftp-user/html/todosalacancha/application/views/index/trivias.php
Line: 135
Function: in_array

File: /home/ftp-user/html/todosalacancha/application/controllers/Index.php
Line: 262
Function: view

File: /home/ftp-user/html/todosalacancha/index.php
Line: 317
Function: require_once

**Comment by carlos-segovia** [comment]
the issue persists. Not solved.

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
Ok working fine now
