### ISSUE TITLE
Backend - crear empresa

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#109]
Al crear una empresa si la URL tiene algún error al darle click a Volver se pierden todos los datos que ingresamos previamente.
No deberiamos perder los datos que ya ingresamos en el formulario.

**Comment by debasishpaul2014** [comment]
can't understand what do you mean

**Comment by oswaldopr** [comment]
No entiendo esto. Si ocurre algún error en la inserción/actualización del registro en la base de datos, no sólo para el campo **url**, el botón [Volver] adquiere la funcionalidad de regresar a la "página atrás" tal como lo haría el navegador, de hecho, es la instrucción que se asigna como acción. Ahora bien, el navegador es el encargado de mantener estos datos y si la página actual proviene de un formulario (como es el caso), se cargan los datos que se enviaron previamente.

**Comment by carlos-segovia** [comment]
No puedo crear una empresa, me esta pidiendo que agregue imagen del Slider, si la agrego igual me la sigue pidiendo.
![image](https://user-images.githubusercontent.com/34341691/38311064-94d57000-37f4-11e8-9662-3c1da15d8dd9.png)

El tema de la URL es así:
1) voy a crear una empresa nueva
2) completo los datos, en URL escribo el nombre de una empresa que ya exista por ej. google.
3) confirmo
4) me sale mensaje de error avisando que google ya existe
5) click en boton Volver
6) vuelve al formulario pero esta totalmente vacio, los datos que ingresé en el paso 2) se pierden todos.

**Comment by oswaldopr** [comment]
1. Probé la creación de empresas directamente en el sitio y no tuve el inconveniente con la validación de imágenes para el _slider_. Registré la empresa **Prueba Prueba** (id: 8). Por otra parte, es raro porque esas imágenes no tienen el atributo de obligatorias así que el navegador no las valida.

2. Para mantener los datos del formulario al presionar el botón [Volver] se ha implementado la solución de forma manual ya que la funcionalidad programada varía entre navegadores. Las imágenes nuevas, al regresar, no se mantienen y no es posible asignarlas nuevamente por una directiva de seguridad en los navegadores (no se puede acceder por programación al sistema de archivos del equipo local).

_Pull Request #119_

**Comment by robertmurer** [comment]
ok
