### ISSUE TITLE
Frontend - Banner

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#111]
The text inside banner must be a loop.
Now if the text is longer than the height the employee have only one chance to read it because it stop and it's not posible to see the begining.

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
I don't see it working here, maybe its my cache the problem

**Comment by debasishpaul2014** [comment]
done, please test with clear browser cache

**Comment by carlos-segovia** [comment]
Done!
