### ISSUE TITLE
Backend - Editar empresa

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#113]
1) que las imagenes se puedan ver/descargar
2) que las imagenes que no son obligatorias/requeridas  tengan un boton que permita borrarlas.

**Comment by oswaldopr** [comment]
Se han programado las funcionalidades requeridas. En el caso de la descarga, sólo aplica a las imágenes que ya estén guardadas en el sitio.

_Pull Request #119_

**Comment by robertmurer** [comment]
Perfecto
