### ISSUE TITLE
Frontend - Bases y Condiciones - Mobile version has no content

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#114]
Bases y condiciones not showing content for mobile version, for web it is ok:

URL http://todosalacancha.sietepuentes.com/google/bases-y-condiciones (user rmurer1 pass rmurer1)

**Mobile**:
![image](https://user-images.githubusercontent.com/35821871/38321120-04add486-380d-11e8-850c-90d25cdf20e1.png)

**Web**:
![image](https://user-images.githubusercontent.com/35821871/38321110-f7ee248a-380c-11e8-94b3-60d801d777e3.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
Perfect
![image](https://user-images.githubusercontent.com/35821871/38445298-50c14c32-39c9-11e8-9048-d5711c09f5f4.png)
