### ISSUE TITLE
Frontend - Trivias - Radiobuttons should not be pre-selected automatically

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#115]
http://todosalacancha.sietepuentes.com/google/trivias
User rmurer10 pass rmurer10

All radiobuttons should be unselected
User did not replied to trivia yet, but as soon as trivia is loaded, there are radiobuttons selected automatically. 

![image](https://user-images.githubusercontent.com/35821871/38439571-7b2dccc6-39b4-11e8-984e-e421e2d63a84.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
Working fine
