### ISSUE TITLE
Frontend - Mobile - Profile image not showing in some pages

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#116]
http://todosalacancha.sietepuentes.com/marvel/
user rmurer pass rmurer

Seems you are using header with different code on each page, we need same code in all pages!!!

Profile image in right side top, appears ok (rounded and uploaded image) only in edit-profile
In other screens, image is not showing, or showing but not circle, let's please use same image as in edit-profile (circle)

Edit-profile (OK)
![image](https://user-images.githubusercontent.com/35821871/38445510-47368032-39ca-11e8-940e-4b2106e1209b.png)

Predictions (Not ok)
![image](https://user-images.githubusercontent.com/35821871/38445519-568c2384-39ca-11e8-89fb-3b37189d998f.png)

Premios (Not ok) it is a sqare not a circle
![image](https://user-images.githubusercontent.com/35821871/38445550-6cb83e7c-39ca-11e8-8605-cd27b6e9333a.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
ok
