### ISSUE TITLE
Frontend - Web Menu version profile image

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#117]
Profile image should be a circle, but in some pages it is a sqare, we need same code for menu in all pages!!!!!

![image](https://user-images.githubusercontent.com/35821871/38445815-7951f280-39cb-11e8-9ff0-2b604694c0d0.png)

**Comment by robertmurer** [comment]
For web it is ok

**Comment by debasishpaul2014** [comment]
done
