### ISSUE TITLE
Frontend - Bases y Condiciones should be in multiple lines

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#118]
Bases y Condiciones must be shown in different lines, as it was saved in database:

**Database in multiple lines**
![image](https://user-images.githubusercontent.com/35821871/38456081-b5fc2dbe-3a56-11e8-9551-7465e111ac47.png)

**Frontend in single line is incorrect**
![image](https://user-images.githubusercontent.com/35821871/38456085-c6195fdc-3a56-11e8-865e-a212f109099f.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
working fine
