### ISSUE TITLE
Frontend - Perfil - Edit image

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#123]
It's not validating the dimension/size of the image and you could not do a crop to fit the img with de circle.

**Comment by debasishpaul2014** [comment]
cant add crop section, it will affect the existing design

**Comment by carlos-segovia** [comment]
validate the size of the image. 
Use Config.php to set profile_max_size_img

**Comment by debasishpaul2014** [comment]
done
