### ISSUE TITLE
Frontend - Pronosticos - BUG

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#124]
for marruecos vs iran i only feel one of numbers with 5 I live empty the other, click on Pronosticar and I get a message that said that my predictions wasn't saved but don't explain why.
After that the form was bloqued and I couldn't insert the pending prediction or other.
![image](https://user-images.githubusercontent.com/34341691/38568757-d5a8079e-3cbf-11e8-8cfa-04ff5243ddc5.png)

**Comment by debasishpaul2014** [comment]
I can't see any issue here

**Comment by carlos-segovia** [comment]
Ahora no se traba pero sigue habiendo issues. Se actualiza en el #131
