### ISSUE TITLE
Frontend - Trivias

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#126]
If you dont answer all the question and submit we receive a message in inglish "Please answer all questions" change it to "Debe completar las tres preguntas"

![image](https://user-images.githubusercontent.com/34341691/38569603-15d6c5e2-3cc2-11e8-821d-66256e7e3aee.png)

**Comment by robertmurer** [comment]
ok

![image](https://user-images.githubusercontent.com/35821871/38614418-7c7be5d8-3d63-11e8-98e2-1731a0a5c079.png)
