### ISSUE TITLE
Frontend - Ranking - wrong position informed to user in ranking

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#128]
http://todosalacancha.sietepuentes.com/marvel/ranking
user rmurer, pass rmurer

1-Login, then go to ranking page
2-There is only one user with points for the company
3-Screen shows user is in position "5" of ranking, this is incorrect, user is in position "1" in the company.

![image](https://user-images.githubusercontent.com/35821871/38614951-57635f86-3d65-11e8-85bf-e885eabb6baf.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by carlos-segovia** [comment]
done!
