### ISSUE TITLE
Frontend - right side timer not shown in some pages

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#129]
We need right side screen using same code in all pages!!! 

http://todosalacancha.sietepuentes.com/google/ranking
user rmurer10
pass rmurer10

Right side timer is not ok in some pages, we need same content in right side.  in predictions it is ok, please check other pages.

**Ranking - wrong**
![image](https://user-images.githubusercontent.com/35821871/38622087-bb81dc00-3d78-11e8-91a9-8eb9182656c0.png)

**Predictions - ok**
![image](https://user-images.githubusercontent.com/35821871/38622069-aff79cda-3d78-11e8-89ae-9badc6947d18.png)

**Trivias wrong**
![image](https://user-images.githubusercontent.com/35821871/38622122-dae609d6-3d78-11e8-9a5e-6a52d314e794.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
ok
