### ISSUE TITLE
Frontend - Predictions page allowing predict matches with less than 24 hours to kickoff

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#130]
http://todosalacancha.sietepuentes.com/google/pronosticos/fase
user rmurer10
pass rmurer10

First match remaining time is 22hours (less than 24 hours).  I am able to change the prediction and save that change, this shouldn't be allowed if timer shows less than 24 hours

![image](https://user-images.githubusercontent.com/35821871/38622425-85f9418a-3d79-11e8-962c-ec01128b8625.png)

**Comment by carlos-segovia** [comment]
solucionado.
