### ISSUE TITLE
Frontend config database setting

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#132]
Hi Debasish, 

Please check if possible to use "abm/config.php" to get database host, user, password from there.

Thanks,

Robert

**Comment by debasishpaul2014** [comment]
its not possible 
SQLSTATE[HY000] [1045] Access denied for user 'todosalacancha'@'localhost' (using password: YES)

**Comment by debasishpaul2014** [comment]
![image](https://user-images.githubusercontent.com/6839637/38772174-3b4744f2-404e-11e8-8f7e-ecbbdeeb4594.png)

**Comment by robertmurer** [comment]
got it
