### ISSUE TITLE
Frontend - Pronosticos Resultado

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#133]
creo el issue para no olvidarnos.
Si el admin no ingresó el resultado en pronosticos no deberia aparecer 0-0, que no aparezca nada.

**Comment by robertmurer** [comment]
Si, buenísimo este tema lo había pensado y me había olvidado.

**Comment by robertmurer** [comment]
Creé issue 165 a Deba, cierro esto.
