### ISSUE TITLE
Frontend - Pronosticar button always viewable in mobile

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#139]
Pronosticar button cannot be seen in mobile, we need to add two more options in dropdown, to predict "Goleador", and "Campeon", instead of having these predictions in slider we will have in dropdown. This was discussed with Debasish over the phone last week

**Pronosticar button should appear always in bottom, and this is how its being seen:**
![image](https://user-images.githubusercontent.com/35821871/38957459-121b04e8-4331-11e8-947e-60b889d1a00f.png)

**Comment by debasishpaul2014** [comment]
done
