### ISSUE TITLE
Predictions page - allows to save predictions like X - 11

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#141]
http://todosalacancha.sietepuentes.com/google/pronosticos/octavos
user rmurer9
pass rmurer9

The steps to reproduce are:
1-Enter 0 in left, and keep X in right, Save
2-Error message appears
3-Enter 8 in right side, keep 0 in left side, Save
4-Message saying predictions were saved appears, page refresh
5-When page refresh, it will be X - 8

Same happens in both sides

**Comment by robertmurer** [comment]
This is not working properly.

http://todosalacancha.sietepuentes.com/google/pronosticos/final
user rmurer8, pass rmurer8

following steps detailed in this issue I was able to save prediction as follows:
![image](https://user-images.githubusercontent.com/35821871/39100667-a4c4d1cc-4663-11e8-8327-78c1ac2b8d6b.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
Tested in mobile working fine 
Yet pending to test in web

**Comment by robertmurer** [comment]
Working fine in web
