### ISSUE TITLE
Frontend - Design issues in Mac and iPhone

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#142]
http://todosalacancha.sietepuentes.com/google/

user y pass:  rmurer7 / rmurer7

Mac
![image](https://user-images.githubusercontent.com/35821871/39138612-bad5beca-46f6-11e8-9286-48fabaf443c2.png)

![image](https://user-images.githubusercontent.com/35821871/39138650-d5b6c23e-46f6-11e8-89a7-385eb14f3c3a.png)

iPhone:
![image](https://user-images.githubusercontent.com/35821871/39138672-e097bad2-46f6-11e8-839c-5dc063e19ea1.png)

**Comment by debasishpaul2014** [comment]
![image](https://user-images.githubusercontent.com/6839637/39204694-21347a92-4816-11e8-806e-f23dc589fc15.png)

**Comment by debasishpaul2014** [comment]
done , please check

**Comment by robertmurer** [comment]
ok
