### ISSUE TITLE
Frontend - Mac (Safari and Chrome)

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#143]
There are few more issues in Safari and Chrome (in MAC).

Scrollbar is not shown so users doesn't know they must scroll
The results and dropdows are a little bit below the line, please see the red boxes (it happens for closed and open predictions with dropdowns).  

![image](https://user-images.githubusercontent.com/35821871/39148593-159433c0-4713-11e8-9808-b7fea94560e8.png)

**Comment by debasishpaul2014** [comment]
![image](https://user-images.githubusercontent.com/6839637/39204703-26d42e34-4816-11e8-91fc-99f5863e7c24.png)

**Comment by debasishpaul2014** [comment]
hi , I can see the scroller

**Comment by robertmurer** [comment]
Hi Deba, problem is in Mac 
I have uploaded the screenshot in Mac the scrollbar is not shown to user

**Comment by robertmurer** [comment]
Deba, scroll in crossbrowser testing page is always viewable or only appears after you scroll with mouse? Also please check there are lot of design issues in your screen shared.

**Comment by robertmurer** [comment]
Deba, we have just double checked with customer, they are not able to see the scrollbar neither in Chrome, nor in Safari, using MAC.  The problem here is users don't know there are more results if they scroll down, so...

1) Can we add some good looking arrow pointing down, in order users know there are more results scrolling down?
or another option
2) Maybe we can show half one row **always** in the bottom part, then users will know there are more records scrolling down

See below screenshot, there is no scrollbar, and we need to do something in the highlighted part

![image](https://user-images.githubusercontent.com/35821871/39249673-8b4a4722-4875-11e8-91a5-b69e8e50f9a4.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
asked customer to check in mac

**Comment by robertmurer** [comment]
Hi Deba, 

Please change the arrow you used for some other with animation (gif), please refer to attached examples customer provided and check which one is better in current design.

![pure-css-scroll-animation-arrow](https://user-images.githubusercontent.com/35821871/39710540-79142e56-51f3-11e8-8f1a-fbef72dd9a28.gif)
![gooey-scroll-arrow](https://user-images.githubusercontent.com/35821871/39710541-7937b7d6-51f3-11e8-981e-e564caa1be36.gif)
![scss-arrow-animation](https://user-images.githubusercontent.com/35821871/39710543-795a76c2-51f3-11e8-9b59-36b11c12aab4.gif)

**Comment by debasishpaul2014** [comment]
the above images will not be applicable. I have added another picture , please check

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
Seems ok, will wait for user customer feedback.
