### ISSUE TITLE
Backend - Permitir username con más de 15 caracteres

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#144]
Hola Oswaldo,

Necesitamos permitir que el campo de nombre de usuario sea de más de 15 caracteres, por favor cambiemos para permitir con un limite de hasta 100 caracteres.

Hay que modificar la tabla:

* empleados.user
* modificar el import del excel para que se permitan también
* permitir el ingreso de hasta 50 caracteres en el abm para el campo usuario
* revisar las validaciones
* permitir caracteres extraños como @ ya que muchos usuarios tendran en este campo su email.

**Comment by oswaldopr** [comment]
Hecho. Se permiten hasta 100 caracteres.

**Comment by robertmurer** [comment]
ok funciona bien.
