### ISSUE TITLE
Frontend - Perfil Timer

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#146]
Perfil page it's not showing the timer
![image](https://user-images.githubusercontent.com/34341691/39161385-d645b066-4746-11e8-92e7-b80fd5b04bc0.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
ok
![image](https://user-images.githubusercontent.com/35821871/39223476-b18684da-4818-11e8-8b71-0bfd6aeb9dd9.png)
