### ISSUE TITLE
Frontend - Pronosticos Flags

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#147]
If the name of the country is large the flag reduce the size.
![image](https://user-images.githubusercontent.com/34341691/39161823-f0843a4a-4748-11e8-91be-e8f94564caf5.png)
All the flags must be the same size. To solve this reduce the font size of the countries

**Comment by debasishpaul2014** [comment]
Tested on Firefox, but can't find out the design issue

**Comment by robertmurer** [comment]
@carlos-segovia please double check in firefox, I have also tested and cannot see the problem

**Comment by robertmurer** [comment]
Este issue lo cerraría....

**Comment by robertmurer** [comment]
Solved!
