### ISSUE TITLE
Frontend - Mobile - predictions 

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#148]
In iPhone there is some space just below the drop downs please remove this space 

![7c18698d-16a4-4329-a007-c3e927a2d3ad](https://user-images.githubusercontent.com/35821871/39185176-ad89302a-479c-11e8-930f-aa1983e2b02c.jpeg)

**Comment by debasishpaul2014** [comment]
done, clear your browser cache  and check

**Comment by robertmurer** [comment]
ok
