### ISSUE TITLE
Front end - Mobile - Predictions

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#149]
In las two phases there are only two matches, in this case the predict button disappears and user is unable to predict (Mobile iPhone)

![bc339e1d-5cf0-4154-8fd1-33acc7eabca9](https://user-images.githubusercontent.com/35821871/39185271-0a60a094-479d-11e8-97b9-357b305678a8.png)

**Comment by debasishpaul2014** [comment]
done
