### ISSUE TITLE
Frontend - New modal for trivias

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#150]
System enhancement
-Every time user clicks in Predictions hyperlink
-Validate: there are active trivia for this company, for the current date, unanswered by user?
-if true: show modal with text “Podés contestar la trivia y tenéis chances de duplicar tus puntos!”
- Modal must have two buttons “Ir a la trivia” and “cerrar”
- If user clicks in “ir a la trivia” redirect to trivias page
- if user clicks in “cerrar” user must be able to predict
- validation should be done every time users click in Pronosticar hyperlink
- if there is no trivia active in company user will not see this modal
- this must be done for web and mobile

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
Please update the message to "¡Podés contestar la trivia y tenés chances de duplicar tus puntos!”

Also please show modal only when user clicks in Menu->Pronosticos hyperlink.  Modal should not appear when user clicks in every phase hyperlink.

Also please update this issue with the files changed for this, as we need to update test site.

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
Please list all files changed

**Comment by robertmurer** [comment]
Please check the font was changed, why? modal text must have right font. It was with right font in previous version.
![image](https://user-images.githubusercontent.com/35821871/39550803-f22fab62-4e38-11e8-9f69-85879d1ec7ef.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
Please inform all files changed with this enhancement

**Comment by robertmurer** [comment]
ok
