### ISSUE TITLE
Frontend- wording update with accent 

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#151]
Please update highlighting words:

Quien should be “Quién”
proximo should be “próximo”
Pronostica should be “Pronosticá”

![a3ce38b3-b879-4519-a0cc-b96b00619d20](https://user-images.githubusercontent.com/35821871/39200139-acf8e84c-47c1-11e8-84b1-d89b9a8b1d9e.jpeg)

**Comment by debasishpaul2014** [comment]
done
