### ISSUE TITLE
Frontend - Dropdown values for prediction right side sort

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#154]
Please sort these two dropdown values in ASC order:
![image](https://user-images.githubusercontent.com/35821871/39223029-35bbe284-4816-11e8-98e9-04bc99b201e4.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
Great
![image](https://user-images.githubusercontent.com/35821871/39377459-9707ef1c-4a2b-11e8-9fc8-eabba0d3511e.png)
