### ISSUE TITLE
Frontend - Predictions page show 0 points if no points for match for user

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#156]
In below screen, if match is "scored=1" and user has no points for that match, please show 0 instead of empty value

![image](https://user-images.githubusercontent.com/35821871/39252386-e93ba9ec-487b-11e8-8a1a-fb4117d2d496.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
Great
![image](https://user-images.githubusercontent.com/35821871/39378663-6f60e7e4-4a2f-11e8-999f-519940d24a25.png)
