### ISSUE TITLE
Frontend - Right side predictions

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#159]
24hs before first match kickoff, the right side "Guardar" button is disabled, this is ok, in addition to that we need to:

1) Disable the two dropdowns (users won't be able to see other options)
2) Hide button "Guardar" 

![image](https://user-images.githubusercontent.com/35821871/39275881-5422a1ca-48bd-11e8-8e6b-4579ecac0b14.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
Please make sure when dropdowns are disabled for selection, the text remains white, I can see the text when disabled is not clear enough because it changed the color.

![image](https://user-images.githubusercontent.com/35821871/39552591-3de92e46-4e40-11e8-8456-8730bf65f11d.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
What about in mobile? I am still able to predict these two drop down options in mobile.

**Comment by robertmurer** [comment]
In mobile this is pending. Please apply same logic in mobile ![Image](https://i.imgur.com/FlDUewJ.jpg)

**Comment by robertmurer** [comment]
done
![image](https://user-images.githubusercontent.com/35821871/39607003-df02c5a2-4f0e-11e8-8bf2-f7a75bc99fed.png)
