### ISSUE TITLE
Frontend - Contact form widget to be added

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#162]
Deba, please add this script in frontend screens, it is expected to show a widget with a contact form with automatic email delivery to customer.  

<script>
// Include the UserVoice JavaScript SDK (only needed once on a page)
UserVoice=window.UserVoice||[];(function(){var uv=document.createElement('script');uv.type='text/javascript';uv.async=true;uv.src='//widget.uservoice.com/wqytnQKrHHYWBd6ezBPyw.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(uv,s)})();

//
// UserVoice Javascript SDK developer documentation:
// https://www.uservoice.com/o/javascript-sdk
//

// Set colors
UserVoice.push(['set', {
  accent_color: '#e23a39',
  trigger_color: 'white',
  trigger_background_color: '#6aba2e'
}]);

// Identify the user and pass traits
// To enable, replace sample data with actual user traits and uncomment the line
UserVoice.push(['identify', {
  //email:      'john.doe@example.com', // User’s email address
  //name:       'John Doe', // User’s real name
  //created_at: 1364406966, // Unix timestamp for the date the user signed up
  //id:         123, // Optional: Unique id of the user (if set, this should not change)
  //type:       'Owner', // Optional: segment your users by type
  //account: { // Account traits are only available on some plans
  //  id:           123, // Optional: associate multiple users with a single account
  //  name:         'Acme, Co.', // Account name
  //  created_at:   1364406966, // Unix timestamp for the date the account was created
  //  monthly_rate: 9.99, // Decimal; monthly rate of the account
  //  ltv:          1495.00, // Decimal; lifetime value of the account
  //  plan:         'Enhanced' // Plan name for the account
  //}
}]);

// Add default trigger to the bottom-right corner of the window:
UserVoice.push(['addTrigger', {mode: 'contact', trigger_position: 'bottom-right' }]);

// Or, use your own custom trigger:
//UserVoice.push(['addTrigger', '#id', { mode: 'contact' }]);

// Autoprompt for NPS® Rating and SmartVote (only displayed under certain conditions)
UserVoice.push(['autoprompt', {}]);
</script>

**Comment by debasishpaul2014** [comment]
javascript is not working, it's not a valid format.  please send me the code in a text file

**Comment by robertmurer** [comment]
[user_voice script.zip](https://github.com/robertmurer/todosalacancha/files/1972493/user_voice.script.zip)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
Please 
1-This is not working, I can see in top left corner, but when I click nothing happens.  Please make it work.
2-Include this widget also in login screen
3-I think it is not working because it is located in top, could you please locate in bottom page in right side predictions 

![image](https://user-images.githubusercontent.com/35821871/39606889-21682898-4f0e-11e8-846c-5b4b72acfb31.png)

**Comment by robertmurer** [comment]
I fixed this.  Deba please update your local files with server files.

**Comment by robertmurer** [comment]
added in right side and working
