### ISSUE TITLE
Frontend - Predictions screen to show current phase based on current date

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#163]
Everytime we click in Predictions hyperlink screen will open and selected phase is "Grupos" /fase
Can we do this logic?

1-Get system date (for instance server date now is July 4th).
2-Based on system date, check which is the next match kickoff date closer than system date, Query will be "select stage_id from partidos where kickoff > NOW() ORDER BY match_id ASC LIMIT 1"
3-Show default screen "predictions" phase based on stage from previous query, for instance, if server date is july 4th, selected default phase (web and mobile) should be "Cuartos"

http://todosalacancha.sietepuentes.com/google/pronosticos/fase

**Comment by debasishpaul2014** [comment]
this can't be done now as I need to change many existing  logic for this page

**Comment by robertmurer** [comment]
lets please hold this change until further notice

**Comment by carlos-segovia** [comment]
1) get system date
2) select min(kickoff), match_id from partidos where kickoff > system_date;
3) If you know the match_id (point 2) you can get the phase and show it in Pronosticos

**Comment by robertmurer** [comment]
Please check the query added and go ahead with this change

**Comment by debasishpaul2014** [comment]
not clear

**Comment by robertmurer** [comment]
What is not clear Debsish? 5 days ago you mentioned you need to change many existing logic, we have detailed the change and also gave the query to identify the phase.

**Comment by debasishpaul2014** [comment]
this functionality is not possible now , as I need to change some existing code

**Comment by robertmurer** [comment]
Fixed, added in left-menu.php, to be moved to config.php

**Comment by mepalacios** [comment]
if the quarterfinals are on July 6 and 7 and the server date is 4, it is correct
