### ISSUE TITLE
Frontend - Trivias page, buttons are moving.

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#164]
Please check in trivias screen, buttons are moving, we need to avoid this.  Attaching video file showing this.

[WhatsApp Video 2018-04-27 at 12.57.09.zip](https://github.com/robertmurer/todosalacancha/files/1955845/WhatsApp.Video.2018-04-27.at.12.57.09.zip)

**Comment by debasishpaul2014** [comment]
I am not getting this error in my browsers chrome, firefox,opera

**Comment by debasishpaul2014** [comment]
I am not be able to produce this error

**Comment by mepalacios** [comment]
Tested with Chrome and with Firefox, the error is not generated, it's ok
