### ISSUE TITLE
Frontend - WEB - Ranking page to show profile picture

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#166]
Deba, please let us know if feasible, and the options you see to add on each username in ranking page, the profile picture (as it is in mobile version).  Will wait for your feedback.
One option could be increase text size and show the image in a circle next to each name.  Please check and revert.

![image](https://user-images.githubusercontent.com/35821871/39383691-99866d44-4a40-11e8-9509-ca6e5728c69b.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
I can see the image, but why the font was replaced? please keep same font it was before
![image](https://user-images.githubusercontent.com/35821871/39606943-829f5776-4f0e-11e8-9b1c-d0319a10ac6a.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
Está funcionando pero no estoy seguro que guste al cliente esto, que opinas @carlos-segovia 
![image](https://user-images.githubusercontent.com/35821871/39657284-decf8d26-4fdc-11e8-9c86-9b8e3f996907.png)

**Comment by carlos-segovia** [comment]
para mi esta bien. Esperemos a ver que dice el cliente.
