### ISSUE TITLE
Frontend - Trivias page shows No Trivia even for user who already replied

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#167]
http://todosalacancha.sietepuentes.com/google/trivias
user rmurer10, pass rmurer10

This user already replied to trivias, when user enters to trivias page, will get "No Trivia" message and this is not correct.

When user logs into trivias page:
- Please show last trivia answered by user, also, please show "respuestas anteriores" button if user replied old trivias.
- If user did not reply to any trivia, then show "No hay trivias para contestar".

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
ok 
![image](https://user-images.githubusercontent.com/35821871/39606968-ad441ec6-4f0e-11e8-8bfc-7a9792da2b53.png)
