### ISSUE TITLE
Frontend - Profile picture is shown rotated

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#169]
In mobile we have the picture taken even vertical or horizontally, when profile is uploaded from mobile it appears rotated and wrongly.

![image](https://user-images.githubusercontent.com/35821871/39534591-49c3d1f4-4e08-11e8-8b1c-108f8c7ace46.png)

**Comment by carlos-segovia** [comment]
ok in Android.

**Comment by carlos-segovia** [comment]
Ok in Iphone too.

**Comment by debasishpaul2014** [comment]
done
