### ISSUE TITLE
Frontend - Trivias page show right answer in different color after trivia is finished 

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#170]
In trivia page 
- if trivia is finished (trivia finish date < sysdate)
- show each “correct” answer for each question in different color (green)

This way user will know if user answers were correct or not.

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
answer must be changed in color only if trivia has been finished, but I have answered a trivia and it changed to green as soon as user replied to it.

http://todosalacancha.sietepuentes.com/google/trivias
rmurer9, rmurer9

![image](https://user-images.githubusercontent.com/35821871/39675587-8abe3e82-5133-11e8-98d8-6dd41588aa53.png)

**Comment by robertmurer** [comment]
I am not able to check this, because the user answers all the questions in trivia id 1, then i change server date, user is able to answer all questions in trivia 2.  But in Trivias page, when user goes to "Respuestas anteriores" button, trivia 1 answers are not showing in user's view.

http://todosalacancha.sietepuentes.com/google/respuestas-anteriores
user rmurer12, pass rmurer12

User is empleado_id 32938, when user goes to Trivias page, user can see Trivia id 2 options to answer, but in Respuestas Anteriores, trivia id 1 answers must appear showing right answer in green.

Refer to screenshots, this is not working fine:

![image](https://user-images.githubusercontent.com/35821871/39680310-8af821aa-5175-11e8-8e2e-64cd253ff352.png)

Screen showing user answered all three questions for trivia id 1
![image](https://user-images.githubusercontent.com/35821871/39680317-9aed03f0-5175-11e8-91c6-2055d66094af.png)

**Comment by robertmurer** [comment]
Tested with rmurer9/rmurer9 working fine 

![image](https://user-images.githubusercontent.com/35821871/39726962-3819490c-5227-11e8-9810-13f02e6531c5.png)
