### ISSUE TITLE
Frontend - Trivias (Web and mobile)

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#172]
User replied to trivia, but after refresh seems user selection is not saved.  User is able to reply to trivia multiple times and functionality is not working properly.

http://todosalacancha.sietepuentes.com/google/trivias
rmurer9 / rmurer9

![image](https://user-images.githubusercontent.com/35821871/39593599-a45d489c-4ee0-11e8-9717-e49efc204ccd.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
ok
