### ISSUE TITLE
Points in the Ranking

### ISSUE THREAD

**Issue by mepalacios** [robertmurer/todosalacancha#175]
Hello Deba, Plaease
Where do the 490 points come from? If it says below that they are 90

![ranking](https://user-images.githubusercontent.com/38966922/39658630-2faaa1d8-4fe5-11e8-80ac-eae6d8defa23.JPG)

**Comment by robertmurer** [comment]
Ahí chequeé la base y está Ok el puntaje, no sería un issue para Deba, tal vez podamos borrar los rankings... ya que la base tiene info vieja digamos.  Lo que tendríamos que ver es cómo mostrar estos puntajes de goleador y campeón y además si hay puntajes de trivias en el diseño actual, porque no los tuvimos en cuenta, es un buen punto.  Solo mostramos en ranking los detalles de puntos obtenidos por partidos, y el total...  es algo que tneemos que ver como lo mostramos en pantalla, dejemos el issue abierto para analizarlo.

Lo que pasa es que el usuario "user" tiene:
-200 puntos por acertar el equipo campeón
-200 puntos por acertar el goleador
-90 puntos por partidos. 

![image](https://user-images.githubusercontent.com/35821871/39658693-b43b6ce4-4fee-11e8-87bf-f1347b3d3568.png)

**Comment by mepalacios** [comment]
bien Roberto ya lo vi, gracias,

**Comment by robertmurer** [comment]
Hola Maria Elena, veo que el issue lo asignaste a Oswaldo pero Oswaldo es quien desarrolló el backend.  Lo removí.

**Comment by robertmurer** [comment]
Este issue lo podemos cerrar?

**Comment by mepalacios** [comment]
Roberto está abierto porque hay que ver como se muestra en esa pantalla los puntos que se obtienen por acertar el goleador y el equipo ganador del mundial, cierto @carlos-segovia ?

**Comment by carlos-segovia** [comment]
lo cierro porque ya se abrio el #180 para ver como se muestran los puntos por acertar el goleador y el equipo ganador del mundial.
