### ISSUE TITLE
Frontend - Predictions page hide text after match id 1 kickoff date

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#177]
If current date (server date) > match id 1 kickoff date (from database)
    hide from user's view the highlighted part below 
"Quedan
timer
Expired
para el mundial"

![image](https://user-images.githubusercontent.com/35821871/39680449-4135866e-5177-11e8-9a4c-5160f990adc6.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
Please make sure logo is in same position after text is hidden.

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
This is ok
![image](https://user-images.githubusercontent.com/35821871/39726990-578f9d40-5227-11e8-8610-9a1ad5314bf0.png)
