### ISSUE TITLE
Frontend - Mobile view in Predictions - Flags over timer

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#178]
In Chrome you can simulate the iPhone 7 plus view with F12-iPhone 7 plus mobile, as you can see the flag and timer are one over the other, please make sure the timer is separated from the flag, check the marks below:

http://todosalacancha.sietepuentes.com/google/pronosticos/fase
user rmurer10, pass rmurer10

![image](https://user-images.githubusercontent.com/35821871/39680501-b10c5b98-5177-11e8-8f6e-31a082e193b0.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
confirmed by customer
