### ISSUE TITLE
Frontend - Timer

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#184]
Rober, esto es lo que te decia ayer. Fijate el tiempo que queda para pronosticar para el primer partido que es 24 hrs antes y el tiempo del timer que dice lo que falta para que comience el mundial estan iguales. El tiempo del timer para que empiece el mundial deberia mostrar eso, cuanto falta para que empiece y esta mostrando cuando falta para 24 hrs antes de que comience. Me explico? 
![image](https://user-images.githubusercontent.com/34341691/39763997-f0a941c4-52b4-11e8-9fa6-066cfcd47bc0.png)

**Comment by robertmurer** [comment]
Cual era la fecha del server?

**Comment by carlos-segovia** [comment]
El timer del partido muestra lo que falta para el partido.
El timer del mundial muestra lo que falta para que empiece el mundial.
Funciona bien.
