### ISSUE TITLE
Frontend - Ranking

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#186]
[ec2-user@ip-172-31-20-8 7puentes]$ date
Wed Jun 27 15:49:17 UTC 2018

user rmurer10
pass rmurer10

company 7puentes

rmurer10 have 140 points for predictions in grupos phase and 140 more for trivias total 280
carlos have only 140 points for predictions.

See below image, rmurer10 is in position 2 but this is wrong, he is in first position.

![image](https://user-images.githubusercontent.com/34341691/39772751-71437e50-52cc-11e8-9a27-abb80ae431ca.png)

in Grupos its not showing the points of the trivias:
![image](https://user-images.githubusercontent.com/34341691/39780296-425fbfa2-52e2-11e8-9453-4a0ba39b4aa1.png)

**Comment by robertmurer** [comment]
moved to new repo
