### ISSUE TITLE
Frontend - Trivias Title

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#187]
See below image. The title of the trivia are showing two phases. This trivia is for Octavos and is showing 
Octavos Grupos
![image](https://user-images.githubusercontent.com/34341691/39780171-d50ecfe2-52e1-11e8-882b-2750342b6f28.png)

in the Trivias Grupo is showing Trivias: Fase. I dont know why but this is wrong.
![image](https://user-images.githubusercontent.com/34341691/39780564-11505916-52e3-11e8-8f8b-71e3b8eb8c2c.png)

**Comment by robertmurer** [comment]
Yo no veo esto que decís, fijate de refrescar el caché o algo así porque yo veo bien, además revisé el código y es imposible que veas Octavos Grupos...

![image](https://user-images.githubusercontent.com/35821871/39791407-e771ecc0-5311-11e8-9991-f4c1f0106c1d.png)

**Comment by robertmurer** [comment]
Fixed

**Comment by mepalacios** [comment]
Probado en PC con Firefox y Chrome
Que fecha tiene el Server ?

Atentamente,
Maria Elena Palacios

2018-05-08 22:13 GMT-04:00 robertmurer <notifications@github.com>:

**Comment by mepalacios** [comment]
@carlos-segovia prueba cuando puedas

**Comment by carlos-segovia** [comment]
Maria Elena, si ya lo probaste y esta bien lo cierro.

**Comment by mepalacios** [comment]
chevere

Atentamente,
Maria Elena Palacios

2018-05-09 15:56 GMT-04:00 carlos-segovia <notifications@github.com>:
