### ISSUE TITLE
empresas - vista listado caracteres extraños

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#21]
Se visualizan caracteres extraños:

--vista listado
![image](https://user-images.githubusercontent.com/35821871/37029699-211c69b4-2117-11e8-88c7-7bc970d48fb0.png)

--vista edición (se ve bien)
![image](https://user-images.githubusercontent.com/35821871/37029748-42989e96-2117-11e8-9119-214de6722084.png)

**Comment by oswaldopr** [comment]
Ver comentarios en **_pull request_ #48**.
