### ISSUE TITLE
empresas - error al agregar empresa con nombre ya existente

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#23]
1) Existe la empresa "google".  Ahora bien creo nueva empresa google, con misma imagen, y devuelve este error, podemos capturar el error y volver a la pantalla de alta de empresas para que el usuario pueda corregir?

Warning: mkdir(): File exists in /var/www/html/development/todosalacancha/abm/empresasProcesar.php on line 53
INSERT INTO empresas (id_empresa, empresa, descripcion, url, bases_condiciones, is_trivia) VALUES (null, 'google', 'test a', 'googleurl', 'test test test','0') No se pudo crear el directorio para la empresa.SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'google' for key 'empresa'

2) Si la URL ya existe da este error:
![image](https://user-images.githubusercontent.com/34341691/37287146-d766aaca-25e2-11e8-8183-3ac9d7cf8981.png)

**Comment by carlos-segovia** [comment]
esto sigue fallando.

**Comment by oswaldopr** [comment]
Ver comentarios en **_pull request_ #48**.
