### ISSUE TITLE
Log actividades de usuarios

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#43]
Necesitamos tener todas las actividades de los usuarios loggeadas, con día y hora, por ejemplo:
- cuando el usuario ingresó
- cuándo el usuario aceptó las condiciones
- cuándo el usuario hizo un pronóstico y para qué partido fue
- cuándo el usuario respondió una trivia
- cuándo el usuario pronosticó el goleador del campeonato y el equipo campeón.

**Comment by carlos-segovia** [comment]
Oswaldo, vi que agregaste campos de fecha y hora donde no habia pero falta loguear:
- los ingresos del usuario al sistema.
- Cuando el usuario aceptó las condiciones.
- Ahora queda registrada la fecha y hora de cuando el usuario hace pronostico de partido, campeón y goleador ademas de cuando contesta trivia pero el usuario puede modificar sus pronosticos y respuestas y solo esta quedando registrado lo último que hizo. Tienen que quedar logueadas todas las actividades.

**Comment by robertmurer** [comment]
@debasishpaul2014 Debasish, this issue is to login all user activities:
-Each user login
-Each time user predicts matches in pronosticos
-Each time user predicts champion team, and max goal scorer
-Each time user replies to a trivia

Please create a new table to log it, we will need timestamp on each activity.

**Comment by robertmurer** [comment]
@debasishpaul2014 which is the table to log user predictions for champion and player?
