### ISSUE TITLE
Empleados - import excel - Operacion Abortada

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#52]
Cuando se lee el excel, si hay algún registro con error, los restantes se deberían guardar igual. 
En el proceso actual, si algún registro falla los restantes no se ingresan en la base de datos.
Creo que mejor si guardamos lo que está bien, e informamos lo que está mal, 
Que pensás?

**Comment by carlos-segovia** [comment]
lo dejaria así para no complicarla mas.
Le habia pedido a Oswaldo que ponga el detalle de los que estan mal para que el que lo sube los pueda ubicar.
si esta apurado y quiere subir solo los que estan bien saca los que pinchan y los vuelve a subir.
Para mi esta bien asi.

**Comment by robertmurer** [comment]
Ok!
