### ISSUE TITLE
empleadosImportExcel.php

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#6]
![image](https://user-images.githubusercontent.com/35821871/36235606-74c204e4-11d0-11e8-9493-7d989887fc7e.png)

If you click Confirmar without selecting a Empresa or without selecting a file you get below message:

![image](https://user-images.githubusercontent.com/35821871/36235646-aadb8424-11d0-11e8-8d5b-790fd5474cbd.png)

This need validation.

**Comment by ralphdegoma** [comment]
Hi this is fixed. I added a validation for the file to be required.

**Comment by carlos-segovia** [comment]
.csv file type validation works fine.

The validation for the empresa is missing. Now we can upload a file without selecting a empresa and this is wrong. empresa must be selected if not the form can be submited.

**Comment by carlos-segovia** [comment]
Solucionado.
