### ISSUE TITLE
Trivia - Calculo de puntos

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#60]
Probé el calculo de puntos y no funcionó para la trivia 1con empleado_id 1

tabla trivias:
![image](https://user-images.githubusercontent.com/34341691/37611397-fd793ba8-2b80-11e8-8e51-271b28b035f4.png)

tabla trivias_respuestas
![image](https://user-images.githubusercontent.com/34341691/37611586-7c90b52e-2b81-11e8-825f-f96e39590eb0.png)

tabla trivias_repuestas_empleados
![image](https://user-images.githubusercontent.com/34341691/37611676-c081ef14-2b81-11e8-93a6-fc7dfc01d4cf.png)

en la tabla puntos empleados solo se insertó un registro para el empleado_id 132 que no habia contestado ninguna pregunta para esta trivia:
![image](https://user-images.githubusercontent.com/34341691/37611765-0a128e90-2b82-11e8-9e7c-eb353c83dbdf.png)

**Comment by carlos-segovia** [comment]
Se realizó una nueva prueba.
El user id 1 tenia 70 puntos en fase grupos, acertó las 3 respuestas de la trivia fase grupos por lo tanto deberia duplicar los puntos obtenido en esta fase, es decir, la trivia deberia sumarle 70 para que quede con un total de 140.
**Se inserto un registro de puntos por la trivia de 50 puntos en vez de 70.**

**Comment by oswaldopr** [comment]
Se ha corregido la rutina del cálculo de puntos por trivias. La modificación hecha para fusionar las fases "Tercer Puesto" y "Final" originó la falla.

**Comment by carlos-segovia** [comment]
Probado y funcionó correctamente.
