### ISSUE TITLE
empresas abm - tamaño upload de imagenes

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#61]
Se debe validar que el tamaño de las imagenes sea <= al definido

Además se debe validar un tamaño máximo de imágen - este tamaño máximo se debe definir en el config.php en kilobytes, ej 500Kb

Los tamaños de las imágenes fueron validados con el maquetador y son como siguen (aplicar al config.php)

**Logo** (Web y Mobile es misma versión no se requieren dos versiones) = 150x90 px
**Slider** Web - 1920 de ancho (1080 o mas de alto podría ser) // Mobile - 800px height (se alargará a lo ancho)
**Premios** Web - 1920 x 1080 o smaller (pero esa proporción).    Mobile - 600px de alto, width no importa porque se ajusta pero podría ser 500px

**Comment by oswaldopr** [comment]
La validación de imágenes ya incluye la rutina para validar el tamaño de los archivos. Una vez definan todos los tamaños los pueden agregar en el **config.php**. Para especificar el tamaño en KB sólo se debe escribir en el parámetro correspondiente lo siguiente: `TAMAÑO-KB * 1024`; por ejemplo, `500 * 1024` validaría tamaños máximos de 500 KB. Esto es porque la validación se realiza en Bytes.

Por otra parte, se realizarán los cambios solicitados en cuanto a las dimensiones de las imágenes. Sin embargo, dejo algunas dudas por aclarar antes de iniciar:

1. > Se debe validar que el tamaño de las imagenes sea <= al definido
    - ¿La validación será por **relación de aspecto para TODAS las imágenes** con unas dimensiones máximas permitidas?
---
2. > **Logo** (Web y Mobile es misma versión no se requieren dos versiones) = 150x90 px
    - ¿Estas dimensiones son fijas o son máximas? Si son fijas **choca** con el primer requerimiento.
    - Se eliminará la segunda imagen para el logo (versión móvil).
---
3. > **Slider** Web - 1920 de ancho (1080 o mas de alto podría ser) // Mobile - 800px height (se alargará a lo ancho)
    - ¿Para la versión web el valor **1920 de ancho** es fijo o es máximo? Si es fijo **choca** con el primer requerimiento.
    - Para validar la relación de aspecto de una imagen se necesitan ambas dimensiones. Indicar **1080 o mas de alto podría ser** impediría que se aplique apropiadamente la validación. Por tanto ¿Se valida la relación de aspecto o se validan las dimensiones por separado? Si el caso es el segundo, se validaría que cada dimensión sea menor igual al valor al parámetro máximo fijado, pudiendo obviarse alguna o ambas dimensiones para evitar la validación.
    - ¿Para la versión móvil el valor **800px height** es fijo o es máximo? Si es fijo **choca** con el primer requerimiento.
    - Para validar la relación de aspecto de una imagen se necesitan ambas dimensiones. Indicar **se alargará a lo ancho** impediría que se aplique apropiadamente la validación. La premisa para este ítem se considerará bajo la misma respuesta que se otorgue para la versión web de este punto.
---
4. > **Premios** Web - 1920 x 1080 o smaller (pero esa proporción). Mobile - 600px de alto, width no importa porque se ajusta pero podría ser 500px
    - ¿Para la versión web se considerarán las dimensiones **1920 x 1080** como máximas y se debe validar la relación de aspecto?
    - Para la versión móvil se presenta la misma situación de ambigüedad que en el punto 3. Se debe definir en base a lo expuesto allí.

**Comment by carlos-segovia** [comment]
Oswaldo, las medidas son las maximas permitidas.
Ej: 100 x 50 si es mayor a 100 o mayor a 50 respectivamente mensaje de error
si es <= a 100 y a 50 es correcto.

**Comment by oswaldopr** [comment]
Se ha cambiado la validación de imágenes según lo requerido. En adelante, **sólo se validará que las dimensiones de una imagen no excedan los parámetros** indicados. En este sentido, las dimensiones pueden variar siempre que se encuentren dentro de los valores establecidos. También, es posible evitar la validación de alguna de las dimensiones asignando el valor `-1` (ilimitado) a su parámetro en **config.php**.

**Comment by carlos-segovia** [comment]
No me deja subir imagenes < al tamaño de config.php
Ni en empresas ni en la imagen de perfil del empleado.

**Comment by robertmurer** [comment]
No entendí como hacer lo de limitar el tamaño de la imagen, podrías por favor poner en el config.php la línea para que quede limitado el size del upload en 500kb?

**Comment by oswaldopr** [comment]
Corregido el problema que impedía aplicar la validación correctamente. Para asignar valores de validación al tamaño de las imágenes, se debe agregar un cuarto parámetro a la función `setImagesFeatures`, por ejemplo:
`setFeaturesImages("$IMAGE_COMPUTER_PREFIX$IMAGE_LOGO_NAME", 300, 168, 500 * 1024);`
Así se valida un tamaño de 500 KB; el cuarto parámetro es **500 * 1024** porque la validación se realiza en Bytes y `1 KB` son `1024 B`. Se puede colocar la multiplicación o el resultado de la misma.

**Comment by robertmurer** [comment]
Ok perfecto!
