### ISSUE TITLE
Error al upload imagen

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#62]
En el abm indica que el logo debe ser de 300x168
Tengo un logo en esas medidas

Logo:
![logo_nestle_300](https://user-images.githubusercontent.com/35821871/37687604-f6f7c38a-2c7a-11e8-9480-c4d11720dcd5.png)

Medidas:
![image](https://user-images.githubusercontent.com/35821871/37687601-f314e838-2c7a-11e8-9641-397461620dd3.png)

Error al hacer upload:
![image](https://user-images.githubusercontent.com/35821871/37687634-15d297d0-2c7b-11e8-98d0-82f08ff3782e.png)

**Comment by robertmurer** [comment]
yo sigo con este problema, carlos porfa validalo vos en tu pc, yo probé de todo (borrar el .js en el server y volver a subirlo, y me funcionó bien para el logo pero no para otras imágenes, como por ej en premios)

![image](https://user-images.githubusercontent.com/35821871/37731635-7a035518-2d21-11e8-8993-523ce32cae47.png)

**Comment by carlos-segovia** [comment]
Lo probé en dos navegadores sin inconvenientes.
