### ISSUE TITLE
empresas abm - editar empresa/validación de imagenes

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#63]
Editando este issue: lo que necesitamos es que al editar una empresa, no se validen los tamaños de las imágenes que ya fueron incluidas, sólo se debe validar cada imagen que se estará haciendo upload, tanto en "agregar empresa" como en "editar empresa"

--------------------------------------------------
Creamos una empresa llamada Fallcut, con la imagen del tamaño esperado.

Al ingresar a empresas, Editar fallcut devuelve alert de error del tamaño de imagen incorrecto, sin embargo la imagen es del tamaño correcto

![image](https://user-images.githubusercontent.com/35821871/37710126-74fe7d26-2ceb-11e8-89de-6c8c2136d352.png)

![image](https://user-images.githubusercontent.com/35821871/37710283-ecd74094-2ceb-11e8-84db-a722531688b1.png)

**Comment by oswaldopr** [comment]
Se ha evitado la activación de la validación, tanto de las dimensiones como del tamaño del archivo, para imágenes que se encuentren previamente cargadas. Para ello se ignoran los parámetros desde **config.php**.

_Pull Request #67_

**Comment by carlos-segovia** [comment]
Listo! probado y funcionando OK
