### ISSUE TITLE
Empresas/Edición error al querer subir una imagen nueva si previamente tuve error de tamaño

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#64]
empresa google
entre a editarla
agregue una imagen de 300x168 que es el tamaño esperado.
NO confirme
quise agregar una imagen en mobile que no es del tamaño esperado (19x13)
me tiro error:
![image](https://user-images.githubusercontent.com/34341691/37774364-be7f09ec-2dbe-11e8-9896-81cd50106f0f.png)
lo cual es correcto
Le dí confirmar para que suba la primer imagen que agregué de 300x168 y me sale el siguiente error:
![image](https://user-images.githubusercontent.com/34341691/37774433-f7f34d28-2dbe-11e8-9018-e693eb0a74c4.png)
Esto no es correcto

**Comment by oswaldopr** [comment]
Comportamiento corregido.

_Pull Request #67_

**Comment by carlos-segovia** [comment]
funciona OK. Listo!
