### ISSUE TITLE
Empleados - Importar Empleados

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#65]
Desapareció el botón para seleccionar el archivo.
![image](https://user-images.githubusercontent.com/34341691/37779390-0c5658ee-2dcb-11e8-8022-7a5f4a4792da.png)

**Comment by oswaldopr** [comment]
El botón se ocultó por los estilos aplicados en los controles de archivo para empresas, estaban de forma general. Ya se ha solventado.

_Pull Request #67_

**Comment by robertmurer** [comment]
Ok, yo lo puedo ver, se puede cerrar

**Comment by carlos-segovia** [comment]
Listo!
