### ISSUE TITLE
Upload excel empleados - error validando email

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#66]
Al subir un excel para empleados, ninguno tiene email. Adjunto el .csv utilizado.
[empleados_ejemplo.zip](https://github.com/robertmurer/todosalacancha/files/1838823/empleados_ejemplo.zip)

El sistema devuelve el siguiente error:

Importación Fallida Se han leído 15692 registros...Registros ignorados: 0Nombres de usuario iguales: 0Nombres de usuario inválidos: 0Nombres de usuario con longitud inválida: 0Contraseñas con longitud inválida: 0Nombres inválidos: 0Nombres con longitud inválida: 0Apellidos inválidos: 0Apellidos con longitud inválida: 0Correos electrónicos inválidos: 0Correos electrónicos con longitud inválida: 1Departamentos con longitud inválida: 0Ubicaciones con longitud inválida: 0¡OPERACIÓN ABORTADA!
--
![image](https://user-images.githubusercontent.com/35821871/37791423-eaea383e-2de7-11e8-8bcf-fcf76c842ecb.png)

**Comment by oswaldopr** [comment]
La validación de longitudes para direcciones de correo-e no excluía las longitudes igual a cero. Corregido.

_Pull Request #67_

**Comment by robertmurer** [comment]
Funciona ok, cerrado
