### ISSUE TITLE
empleadosProcesar.php?a=uploadExcel

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#7]
I upload attached .csv with 5 employes:

username;password;nombre;apellido
pepe;pepe;pepito;pepiton
carlos ;carlos1;carlos2;carlos3
robert;test;roberto;murer
robert;test;roberto;murer
;;;
the last one have all the values empty

this is the result:
![image](https://user-images.githubusercontent.com/34341691/36235904-fe22d2c6-11d1-11e8-97cd-5f49065b22b0.png)
what happen with the other 2 employess?

**Comment by ralphdegoma** [comment]
In the last two employees this is what happened.

The second to the last was inserted named roberto, since the last employee is identical to the 2nd to the last . The last one will not be inserted. As you can see roberto is in the list of username that didnt inserted.

**Comment by carlos-segovia** [comment]
1) I upload the file empleados_ejemplo.csv with below content:

**Comment by carlos-segovia** [comment]
Continuamos este con el issue #28
