### ISSUE TITLE
Error al crear un usuario que ya existe (pero existe en otra empresa)

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#70]
Quiero crear usuario "rmurer1" para id empresa 3 (Fallcut) pero me devuelve error que el usuario ya existe, este usuario existe para la empresa 2 (google) pero no para la 3 (Fallcut)

![image](https://user-images.githubusercontent.com/35821871/37875205-65eeff3e-3012-11e8-9d69-48c4861b05b2.png)

![image](https://user-images.githubusercontent.com/35821871/37875209-7dd1645c-3012-11e8-810a-38dd7ea3eb05.png)

![image](https://user-images.githubusercontent.com/35821871/37875214-8ad1190e-3012-11e8-87df-3a7f71b4d5b8.png)

http://todosalacancha.sietepuentes.com/abm/empleadosABM.php?a=agregar&id_empresa=3&id_empleado=&username_empleado=rmurer1&nombre_empleado=222222&apellido_empleado=222222&correo_e_empleado=&departamento_empleado=rmurer1&ubicacion_empleado=rmurer1&status_empleado=1&msg_username= El nombre de usuario ya existe

**Comment by oswaldopr** [comment]
Se ha restringido la validación sólo a la empresa seleccionada. Esto se había aplicado pero sólo en la importación de empleados.

**Comment by carlos-segovia** [comment]
Probé desde el archivo y desde agregar. 
Pude registrar un mismo nombre de usuario en distintas empresas.
Funciona OK
