### ISSUE TITLE
URL company, changes to empresas.empresa, instead of empresas.url

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#72]
Hi, seems there is an issue with URL

I have created empresa "Test Empresa Name" as name.  And "testempresa" as URL.
Now when I enter http://todosalacancha.sietepuentes.com/testempresa, it redirects me to http://todosalacancha.sietepuentes.com/ and show error message, see below

![image](https://user-images.githubusercontent.com/35821871/37875358-55382f7e-3014-11e8-8cbd-4e2caa4a4cee.png)

![image](https://user-images.githubusercontent.com/35821871/37875386-9fcfeb76-3014-11e8-99b1-b37a08373c6e.png)

**Comment by robertmurer** [comment]
Ok but this is not working fine.  Please enter  http://todosalacancha.sietepuentes.com/testempresa in your browser and check what happens.... it must show the login page for "testempresa"

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
ok
