### ISSUE TITLE
calculos - puntos por partido

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#77]
Hay un tema con los cálculos, cerré varios partidos y siempre calculó 0 puntos para todos los empleados, el ejemplo que dejo abajo es un partido el id 11, que finalicé con empate 3=3, hay usuarios que pronosticaron empate, incluso el resultado exacto 3=3, sin embargo a todos se les asignó 0 puntos:

![image](https://user-images.githubusercontent.com/35821871/37937454-1f4a947a-3130-11e8-93d3-ebcb7c21f6ed.png)

![image](https://user-images.githubusercontent.com/35821871/37937411-f3a78d96-312f-11e8-971c-7dd19c5c5026.png)

![image](https://user-images.githubusercontent.com/35821871/37937404-e11e0baa-312f-11e8-90cb-2ed7e8e8f362.png)

**Comment by oswaldopr** [comment]
Corregido el procedimiento de cálculo de puntos por partidos. El problema se presentó con la implementación de fusionar la fase "tercer puesto" con "final".

**Comment by robertmurer** [comment]
Funciona ok
