### ISSUE TITLE
.csv format is wrong

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#8]
@ralphdegoma this issue is not your fault but we have to correct it.

csv is comma separated value and we are uploading a file with all the values in one column with ; separator.
If you open it with Excel you will not see the commas 
![image](https://user-images.githubusercontent.com/34341691/36236239-cada0c70-11d3-11e8-8331-52d7b92ef942.png)

but in a notepad you will see the comma separator.
username,password,nombre,apellido
pepe,pepito ,pepiton ,pepon
carlos,carlos1,carlos ,one
robert,pass2,Roberto,Murer

**Comment by ralphdegoma** [comment]
this is now fixed.

**Comment by carlos-segovia** [comment]
I couldn't tested. 
refer to below comment:
https://github.com/robertmurer/todosalacancha/issues/7#issuecomment-366526822

**Comment by carlos-segovia** [comment]
Dejamos ; como separador
