### ISSUE TITLE
Frontend - Editprofile - fixes

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#80]
1) Upload image will need some functionality to crop image in order to fit the image profile (circle) from html templates
2) User should be able to edit profile (only upload picture) with no password change.  This is not allowed currently.
3) Password field should be type "password" instead of text.
4) This type of messages should be in spanish, i.e.: 
Password & confirm password are not same! - La contraseña debe coincidir

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
ok
