### ISSUE TITLE
Frontend - Pronosticos layout

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#82]
1) Reduce font size to avoid two line team name
![image](https://user-images.githubusercontent.com/35821871/38026035-fa965b1e-3260-11e8-9adb-7f4fb70bd818.png)

2) Fix layout in below marks...
![image](https://user-images.githubusercontent.com/35821871/38026121-47fe84a8-3261-11e8-9627-3fef75252630.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
ok
