### ISSUE TITLE
Layout - Changes

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#85]
There are few changes needed in layout:

- Profile image, it's not showed correctly, in design there is a circle in functionality we are showing a square. 
- Texto "Completá los resultados de los siguientes partidos antes del viernes 15/6 a las 18:00 Buena suerte!" cambiarlo por: "Empezá a completar tus pronósticos **antes del jueves 14/6 a las 12pm** Buena suerte!"

**Comment by debasishpaul2014** [comment]
cant understand

**Comment by robertmurer** [comment]
OK @debasishpaul2014 , this issue is not assigned to you, please focus on those ones assigned to you.
