### ISSUE TITLE
backend - upload imagen empleado

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#87]
En el backend cuando se sube una imagen del empleado, tenemos que hacer la misma funcionalidad que se haga en el front, para que se elija el área circular tal cual va en el front....
Otra opción es sacar el img upload del usuario del backend.... y que cada usuario suba su imagen desde el front únicamente.

**Comment by carlos-segovia** [comment]
Para mi tenemos que dejar la opción de agregar/editar img en el back también.

Lo del área circular si lo hace Deba que lo haga también en el back.

**Comment by debasishpaul2014** [comment]
cant understand

**Comment by robertmurer** [comment]
@debasishpaul2014 this issue is not assigned to you, please focus only in issues you are assigned.
