### ISSUE TITLE
Frontend - Trivias - Mobile not showing user selection

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#93]
In web version, trivia shows user selection (trivia was already replied)
![image](https://user-images.githubusercontent.com/35821871/38174477-fca96072-35a3-11e8-9e66-b47e71df0c0b.png)

In mobile version, trivia shows options unselected this is an issue
![image](https://user-images.githubusercontent.com/35821871/38174481-091191fe-35a4-11e8-8e7c-6e30a4ee0461.png)

**Comment by debasishpaul2014** [comment]
working on the design issue

**Comment by robertmurer** [comment]
ok
