### ISSUE TITLE
Frontend - Predictions - Save records with X in any side should not be allowed

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#94]
When user submits any prediction with X in any of both sides, modal appears saying "predictions were saved" but this is incorrect, we must show user there are errors in any prediction if user saved with X in any side.
Message to display in this case is "Sus pronósticos no se guardaron, por favor verifique" and we should focus in the wrong prediction.

![image](https://user-images.githubusercontent.com/35821871/38174539-228c1d4c-35a5-11e8-9229-e872df3c8bda.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
This is not working as expected...

The alert is correct, but after click OK in alert message, it shows the message of confirmation:

This alert is correct, 
![image](https://user-images.githubusercontent.com/35821871/38279648-97b91902-3777-11e8-8162-422efb96c35b.png)

but after I click OK I get this (this is not correct, it must not be shown if previous alert appeared)
![image](https://user-images.githubusercontent.com/35821871/38279672-b0957146-3777-11e8-98e8-485387cd9be1.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
Ok
