### ISSUE TITLE
Frontend - Pronosticos modal

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#95]
Please add a button in modal with label "Cerrar" and same design as button "Pronosticar".  The function of this button is to close the modal.

![image](https://user-images.githubusercontent.com/35821871/38174558-897d6b8c-35a5-11e8-8608-bdd7806a5fc3.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
ok
