### ISSUE TITLE
Frontend - Ranking - Grupos button not working fine

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#96]
In ranking page, the "Grupos" button only works if clicked in the top, in the selected area the hyperlink is not working.

![image](https://user-images.githubusercontent.com/35821871/38174630-86672ed2-35a6-11e8-923c-5135f7272af3.png)

**Comment by robertmurer** [comment]
Can't you fix this design issue?

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
Ok working fine
