### ISSUE TITLE
Backend - Error editando empresas

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#97]
1) Al querer editar una empresa indica que se debe subir una imagen que ya fue agregada cuando la empresa se creó y no me deja continuar

Me sucede con la empresa "marvel" http://todosalacancha.sietepuentes.com/abm/empresasABM.php?a=editar&id=5 

![image](https://user-images.githubusercontent.com/35821871/38176326-14082b4e-35c3-11e8-8fe4-ee06bf36c7c1.png)

2) Permitir símbolos como "!" y "?" en los campos de descripción.

**Comment by oswaldopr** [comment]
1. Yo no tuve inconvenientes con la validación de imágenes.
2. Se han permitido los caracteres indicados.

**Comment by carlos-segovia** [comment]
Oswaldo, tuve el mismo problema que Roberto pero solo con esta empresa y con la misma img del premio. Le di editar, NO modifiqué nada y le di Confirmar y me pasó lo mismo.

Lo de los caracteres ! y ? anda bien.

**Comment by oswaldopr** [comment]
Corregido. Se presentaba sólo para el logo y la falla era producto de no inhabilitar la imagen de la versión móvil, sólo la había ocultado.
_Pull Request #112_

**Comment by carlos-segovia** [comment]
Listo! funciona OK
