### ISSUE TITLE
Frontend - Edit profile screen - Wrong location of profile image

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#98]
Profile image should be in top right corner, in this view it's wrongly located.
Menu item icon is not appearing in left upper corner.

![image](https://user-images.githubusercontent.com/35821871/38176353-a6417b1e-35c3-11e8-80a2-dfbbd1ae2994.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
Now the issue is: the profile image is not shown, only appears the icon but not my profile image uploaded in mobile version

Check: http://todosalacancha.sietepuentes.com/marvel/edit-profile  (rmurer/rmurer)


![image](https://user-images.githubusercontent.com/35821871/38279838-a01592e6-3778-11e8-80db-c0ad25f06dc4.png)



![image](https://user-images.githubusercontent.com/35821871/38279833-8b6234a8-3778-11e8-8309-80288d48fb16.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
ok
