### ISSUE TITLE
Backend - Empresas (Agregar y Editar)

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#99]
Estos dos campos no se usarán ya que en el banner en frontend usamos el logo.
Por favor ocultar por ahora en el código (no eliminarlo por las dudas que lo pidan), y quitar la validación de obligatorio en ambos campos (tanto al agregar y editar).

![image](https://user-images.githubusercontent.com/35821871/38176391-160869a8-35c4-11e8-9a0d-d973322f07cd.png)

**Comment by oswaldopr** [comment]
Hecho.

**Comment by carlos-segovia** [comment]
Listo. No se ven mas estos dos campos ni se validan en agregar y editar.
